### ISSUE TITLE
Distribution?

### ISSUE THREAD

**Issue by petemounce** [joeypiccola/PSWindowsUpdate#3]
Hi there - how is this distributed? Is there a PSGet module, or a chocolatey package? I notice this is a fork - is the upstream no longer maintained...?

A section to the readme about how to download and install this would be really welcome.

**Comment by joeypiccola** [comment]
Hey Pete,

The main branch is managed outside of Github by Michal Gajda. It's currently on version 1.5.2.6 and available for download (e.g. Install-Module) via the PowerShell Gallery. Unless you need something that is found only in my fork, I'd suggest you use the latest version. 

On a side note, I originally forked PSWindowsUpdate thinking Michal abandoned the module\project. However, he has not. The current version 1.5.2.6 was published on 2017-04-04.

Regards, 
Joey
